### ISSUE TITLE
uncompilable with clang and gcc

### ISSUE THREAD

**Issue by ErickDaCoder** [tsyrogit/zxcvbn-c#29] opened 2022-04-11 00:55 UTC
just tested g++ and it works fine, but compiling with clang (Debian clang version 13.0.1-3, target: x86_64-pc-linux-gnu) gives tons of linker errors.
i also had to change the quote style in zxcvbn.c from <angled> to "quoted". not sure if this is by design or just a mistake.
c++ and c compile logs are different so [here's the c log](https://paste.sh/rjlgn3WZ#uTSjPGfHu2OsUrLJMpEC2GrF), and [here's the c++ log](https://paste.sh/x4fduW3J#rX-Ahfmb7rV2bTzSMFE4ZYv5).

**Comment by ErickDaCoder** [comment] 2022-04-12 09:14
if you use g++ compiling works, but lo and behold, gcc doesn't work. again, in the linker stage. it gives nearly the exact same stderr as clang.

**Comment by tsyrogit** [comment] 2022-04-15 20:53
On my system, both compilers work without error. I built the library and test program with the makefile.
The undefined reference to log is because you didn't link with the maths library.
The undefined reference to operator delete[] and operator new[] is because a C++ system library wasn't used. This suggests either a broken  compiler or a command line option was given to not link with the system libraries.

These errors are not caused by zxcvbn-c, so I am closing this issue.

**Closed by tsyrogit** 2022-04-15 20:53 UTC

**Comment by ErickDaCoder** [comment] 2022-04-15 21:19
Oh ok thanks!
